function Hd = lp5Hz
%LP5HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Feb-2018 13:10:42

N     = 120;   % Order
Fpass = 5;     % Passband Frequency
Apass = 0.01;  % Passband Ripple (dB)
Astop = 80;    % Stopband Attenuation (dB)
Fs    = 512;   % Sampling Frequency

h = fdesign.lowpass('n,fp,ap,ast', N, Fpass, Apass, Astop, Fs);

Hd = design(h, 'equiripple', ...
    'StopbandShape', 'flat');



