function y = lp5Hz_execute(x)
%LP5HZ_EXECUTE Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Feb-2018 14:05:00

persistent Hd;

if isempty(Hd)
    
    N     = 120;   % Order
    Fpass = 5;     % Passband Frequency
    Apass = 0.01;  % Passband Ripple (dB)
    Astop = 80;    % Stopband Attenuation (dB)
    Fs    = 512;   % Sampling Frequency
    
    h = fdesign.lowpass('n,fp,ap,ast', N, Fpass, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


