function y = ecg_bandpass(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 25-Mar-2018 11:23:06

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 0.5;  % First Stopband Frequency
    Fpass1 = 5;    % First Passband Frequency
    Fpass2 = 15;   % Second Passband Frequency
    Fstop2 = 45;   % Second Stopband Frequency
    Astop1 = 50;   % First Stopband Attenuation (dB)
    Apass  = 1;    % Passband Ripple (dB)
    Astop2 = 50;   % Second Stopband Attenuation (dB)
    Fs     = 100;  % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'passband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

