function y = hp1Hz(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 20-Mar-2018 20:35:09

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.8;   % Stopband Frequency
    Fpass = 1;     % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 1;     % Passband Ripple (dB)
    Fs    = 1000;  % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

