function y = hp1Hz(x)
%HP1HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 22-Mar-2018 20:31:08

persistent Hd;

if isempty(Hd)
    
    Fstop = 0.45;  % Stopband Frequency
    Fpass = 1;     % Passband Frequency
    Astop = 60;    % Stopband Attenuation (dB)
    Apass = 1;     % Passband Ripple (dB)
    Fs    = 100;   % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


