function y = 50Hz notch(x)
%50HZ NOTCH Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Feb-2018 16:06:38

persistent Hd;

if isempty(Hd)
    
    N  = 6;        % Order
    F0 = 0.19531;  % Center frequency
    Q  = 2.5;      % Q-factor
    
    h = fdesign.notch('N,F0,Q', N, F0, Q);
    
    Hd = design(h, 'butter', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


