function y = bp5_50Hz(x)
%BP5_50HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Feb-2018 12:04:03

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 0.35;  % First Stopband Frequency
    Fpass1 = 0.45;  % First Passband Frequency
    Fpass2 = 0.55;  % Second Passband Frequency
    Fstop2 = 0.65;  % Second Stopband Frequency
    Astop1 = 80;    % First Stopband Attenuation (dB)
    Apass  = 1;     % Passband Ripple (dB)
    Astop2 = 80;    % Second Stopband Attenuation (dB)
    Fs     = 512;   % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


