function y = lp1Hz(x,fs)
%LP1HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Feb-2018 16:29:00

persistent Hd;

if isempty(Hd)
    
    N     = 20;  % Order
    Fpass = 1;   % Passband Frequency
    Apass = 1;   % Passband Ripple (dB)
    Astop = 80;  % Stopband Attenuation (dB)
    Fs    = fs;   % Sampling Frequency
    
    h = fdesign.lowpass('n,fp,ap,ast', N, Fpass, Apass, Astop, Fs);
    
    Hd = design(h, 'ellip', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


