function y = lp5Hz(x)
%LP5HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Feb-2018 12:16:11

persistent Hd;

if isempty(Hd)
    
    N     = 20;   % Order
    Fpass = 5;    % Passband Frequency
    Apass = 1;    % Passband Ripple (dB)
    Fs    = 512;  % Sampling Frequency
    
    h = fdesign.lowpass('n,fp,ap', N, Fpass, Apass, Fs);
    
    Hd = design(h, 'cheby1', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


